# Configuration du site
title: BlackMusic Theme
description: Thème Jekyll BlackMusic

# Configuration du thème
theme: jekyll-theme-minimal

# Configuration du thème sombre
blackmusic:
  accent_color: "#ff0000" # Couleur d'accentuation de votre choix
